networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "433:433"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    
  backend:
    build:
      context: ./back
    networks:
      - dev

  frontend:
    build:
      context: ./front
    networks:
      - dev